### PR TITLE
feat: pico connect support

### PR DESCRIPTION
**Pull request by lonelyicer**
Support for PICO Connect using log parsing with refactored settings

### CODE REVIEW

**Comment by DangerKiddy** [comment]
Hey, I love how you refactored settings class and context menu options, appreciate it!
I'm wondering, is it me missing something or you're not using `IsCharging` function in PicoConnect class? https://github.com/lonelyicer/Headset-Battery-Info/blob/998ee02b2f6527601a3a2c379050bf51987ae2e9/PicoConnect.cs#L64

**Comment by lonelyicer** [comment]
I didn't implement `IsCharging`

**Comment by DangerKiddy** [comment]
I see, I'll implement it and push your PR

**Comment by lonelyicer** [comment]
ok, thanks

**Comment by DangerKiddy** [comment]
@lonelyicer I've edited a bit the way how you get battery percentage for everything (I didn't notice your fix for controller active so I fixed it myself with a different way), take a look if everything looks good for you and let me know that I can push

**Review by lonelyicer — COMMENTED** [review]
everything looks good!

**Pull request merged**
